#!/bin/bash

#PBS -l select=3:ncpus=24:mpiprocs=24:nodetype=haswell_reg
#PBS -P CSCI1142
#PBS -q normal
#PBS -l walltime=08:00:00
#PBS -o job-10k10k.out
#PBS -e job-10k10k.err
#PBS -m abe
#PBS -M blrdav002@myuct.ac.za
#PBS -N 10k10k_1

ulimit -s unlimited

module purge
module load chpc/python/3.7.0

cd $PBS_O_WORKDIR
nproc=`cat $PBS_NODEFILE | wc -l`
mpirun -np $nproc python3 -m mpi4py.futures generate_map.py
